-- AI Chief of Staff — real per-agent ownership + RLS lockdown (2026-07-19).
--
-- chiefs_inventory/chiefs_clients/chiefs_matches/chiefs_pipeline were
-- originally built with `FOR ALL TO anon, authenticated USING (true)` so an
-- agent could use the whole tab with zero sign-in (a per-browser
-- localStorage fingerprint stood in for a real identity — see _chiefsId()
-- in js/chiefs.js). Building a PUBLIC AI Concierge link that embeds an
-- agent_id in a shareable URL (#concierge=<agentId>, added the same day as
-- this migration) made that pre-existing gap materially worse: any caller
-- who already knew or guessed an agent_id could read/write that agent's
-- ENTIRE workspace — real client PII (names/phones/emails/budgets),
-- pocket-listing prices, deal-pipeline/commission data — via a direct
-- Supabase REST call using the public anon key. This migration closes it
-- for good by requiring a real, signed-in Supabase identity to own any row.
--
-- Run this once in Supabase SQL Editor. Requires supabase-chiefs-schema.sql
-- to already be applied (it is). js/chiefs.js now REQUIRES sign-in to use
-- AI Chief of Staff at all (matches the existing "Sign In Required" gate
-- pattern already used by Social Media Manager) — anonymous fingerprint
-- access is retired for real use, but existing fingerprint-owned data is
-- NOT deleted or orphaned: claim_chiefs_workspace() below lets a real
-- account re-point its own past anonymous data to itself in one click,
-- and js/chiefs.js surfaces that offer automatically on first sign-in when
-- a local fingerprint is found.

-- 1) Drop the old blanket "anyone, no ownership check" policies.
drop policy if exists "chiefs_inv_anon" on chiefs_inventory;
drop policy if exists "chiefs_cli_anon" on chiefs_clients;
drop policy if exists "chiefs_mat_anon" on chiefs_matches;
drop policy if exists "chiefs_pip_anon" on chiefs_pipeline;

-- 2) Real ownership: every row can only be read/written by the signed-in
--    Supabase user whose auth.uid() matches its own agent_id. No more anon
--    role in any of these 4 policies at all — a signed-out visitor gets
--    zero access to any of this data via direct REST, full stop.
create policy "chiefs_inv_owner" on chiefs_inventory
  for all to authenticated
  using (auth.uid()::text = agent_id)
  with check (auth.uid()::text = agent_id);

create policy "chiefs_cli_owner" on chiefs_clients
  for all to authenticated
  using (auth.uid()::text = agent_id)
  with check (auth.uid()::text = agent_id);

create policy "chiefs_mat_owner" on chiefs_matches
  for all to authenticated
  using (auth.uid()::text = agent_id)
  with check (auth.uid()::text = agent_id);

create policy "chiefs_pip_owner" on chiefs_pipeline
  for all to authenticated
  using (auth.uid()::text = agent_id)
  with check (auth.uid()::text = agent_id);

-- 3) One narrow, deliberate public exception: the AI Concierge's entire
--    premise is showing a prospect an agent's REAL, currently-available
--    inventory — the same information that agent would show any buyer
--    directly (price/area/beds/size), not confidential data. Public SELECT
--    only, and only for rows the agent has marked available/pocket (never
--    sold/under_offer/expired, which could carry confidential negotiation
--    context) — no anon INSERT/UPDATE/DELETE at all, so a listing can still
--    only ever be created or edited by its real owner via policy #2 above.
create policy "chiefs_inv_public_read" on chiefs_inventory
  for select to anon
  using (status in ('available','pocket'));

-- 4) chiefs_clients/chiefs_matches get ZERO anon access of any kind — real
--    client PII and match data. The AI Concierge's client-save/auto-match
--    step no longer writes directly from the browser with the anon key at
--    all; it now goes through a validated, rate-limited, service-role
--    server endpoint instead (api/chiefs-embed.js, action=concierge-save)
--    — see that file's own comment for why a public write surface can never
--    be a bare client-side insert into a table like this one.

-- 5) Migration path for existing anonymous-fingerprint users (agent_id like
--    'cfp_%', generated by the old localStorage-only identity in
--    js/chiefs.js's _chiefsId()). Lets a real signed-in account claim its
--    own past data in one atomic operation instead of it being silently
--    orphaned by policy #2 above. Fingerprints are a random 12-character
--    string with a ~3×10^21 search space (not brute-forceable) — callable
--    only by an authenticated user, and only re-points rows, never reads
--    or exposes anyone else's data in its response.
create or replace function claim_chiefs_workspace(p_fingerprint text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid text := auth.uid()::text;
  v_inv int; v_cli int; v_mat int; v_pip int;
begin
  if v_uid is null then
    return json_build_object('ok', false, 'error', 'not signed in');
  end if;
  if p_fingerprint is null or p_fingerprint !~ '^cfp_[a-z0-9]+$' then
    return json_build_object('ok', false, 'error', 'invalid fingerprint');
  end if;

  update chiefs_inventory set agent_id = v_uid where agent_id = p_fingerprint;
  get diagnostics v_inv = row_count;
  update chiefs_clients set agent_id = v_uid where agent_id = p_fingerprint;
  get diagnostics v_cli = row_count;
  update chiefs_matches set agent_id = v_uid where agent_id = p_fingerprint;
  get diagnostics v_mat = row_count;
  update chiefs_pipeline set agent_id = v_uid where agent_id = p_fingerprint;
  get diagnostics v_pip = row_count;

  return json_build_object('ok', true, 'inventory', v_inv, 'clients', v_cli, 'matches', v_mat, 'pipeline', v_pip);
end;
$$;

grant execute on function claim_chiefs_workspace(text) to authenticated;
